apiVersion: v1
kind: ServiceAccount
metadata:
  name: oran-adapter
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oran-adapter-manager-role
rules:
- apiGroups:
  - hardware.ran.example.com
  resources:
  - opticaldevices
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - hardware.ran.example.com
  resources:
  - opticaldevices/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - hardware.ran.example.com
  resources:
  - opticaldevices/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oran-adapter-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oran-adapter-manager-role
subjects:
- kind: ServiceAccount
  name: oran-adapter
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oran-adapter
  namespace: default
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: oran-adapter
      containers:
      - name: manager
        image: oran-adapter:latest
        imagePullPolicy: IfNotPresent
        command:
        - /manager
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
