apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xopticaldevice-to-hardware
  labels:
    provider: oran
spec:
  compositeTypeRef:
    apiVersion: ran.example.com/v1alpha1
    kind: XOpticalDevice
  resources:
  - name: opticaldevice
    base:
      apiVersion: hardware.ran.example.com/v1alpha1
      kind: OpticalDevice
      metadata:
        name: my-optical-device # This will be overwritten by the claim name
    patches:
    - fromFieldPath: "metadata.name"
      toFieldPath: "metadata.name"
    - fromFieldPath: "spec.location"
      toFieldPath: "spec.location"
    - fromFieldPath: "spec.controllerConfig.hostname"
      toFieldPath: "spec.controllerConfig.hostname"
    - fromFieldPath: "spec.controllerConfig.port"
      toFieldPath: "spec.controllerConfig.port"
    - fromFieldPath: "spec.parameters.bandwidth"
      toFieldPath: "spec.parameters.bandwidth"
    - fromFieldPath: "spec.parameters.laserPower"
      toFieldPath: "spec.parameters.laserPower"
    - fromFieldPath: "spec.parameters.channel"
      toFieldPath: "spec.parameters.channel"
