apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xopticaldevices.ran.example.com
spec:
  group: ran.example.com
  names:
    kind: XOpticalDevice
    plural: xopticaldevices
  claimNames:
    kind: OpticalDeviceClaim
    plural: opticaldeviceclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              location:
                type: string
                description: "The location of the device."
              controllerConfig:
                type: object
                description: "Connection configuration for the local controller."
                properties:
                  hostname:
                    type: string
                    description: "The hostname or IP of the controller."
                  port:
                    type: integer
                    description: "The port number for the device management interface."
                    minimum: 1
                    maximum: 65535
                required:
                - hostname
                - port
              parameters:
                type: object
                description: "Desired hardware parameters."
                properties:
                  bandwidth:
                    type: string
                    description: "The configured bandwidth of the device."
                    pattern: "^[0-9]+(G|M|K)bps$"
                  laserPower:
                    type: string
                    description: "The power of the laser."
                    pattern: "^[0-9.]+(dBm)$"
                  channel:
                    type: integer
                    description: "Optional optical channel number."
                required:
                - bandwidth
                - laserPower
            required:
            - location
            - controllerConfig
            - parameters